[package]
name = "ply-hash-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
ply-span = { workspace = true }
ply-syntax = { workspace = true }
ply-derive = { workspace = true }
ply-core = { workspace = true }
ply-hash = { workspace = true }
ply-eval = { workspace = true }
ply-std = { workspace = true }
indexmap = { workspace = true }
