//! Generates the corpus's table of its own package's sources: every `.ply` module of
//! `crates/ply-corpus/ply`, named by its stem, in sorted order, plus the manifest. The corpus
//! binary embeds them so it is self-contained; the table lands in dep-info through the
//! `include_str!`s it holds.

use std::path::Path;

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("ply");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut modules: Vec<(String, std::path::PathBuf)> = Vec::new();
    for entry in std::fs::read_dir(&dir).expect("the corpus package directory reads") {
        let path = entry.expect("a directory entry").path();
        if path.extension().is_some_and(|x| x == "ply") {
            println!("cargo:rerun-if-changed={}", path.display());
            let name = path
                .file_stem()
                .expect("a .ply file has a stem")
                .to_string_lossy()
                .into_owned();
            modules.push((name, path));
        }
    }
    modules.sort();
    let manifest = dir.join("ply.pkg");
    assert!(
        manifest.is_file(),
        "the corpus package holds a ply.pkg at {}",
        manifest.display()
    );
    println!("cargo:rerun-if-changed={}", manifest.display());

    let mut out = String::from(
        "/// The corpus package's own modules, one per file of `crates/ply-corpus/ply`, each named\n\
         /// by its stem. Generated by `build.rs` from the package directory.\n\
         pub const CORPUS_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &modules {
        out.push_str(&format!(
            "    ({name:?}, include_str!({:?})),\n",
            path.display().to_string()
        ));
    }
    out.push_str(
        "];\n\n/// The corpus package's manifest.\npub const CORPUS_MANIFEST: &str = include_str!(",
    );
    out.push_str(&format!("{:?});\n", manifest.display().to_string()));

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set for a build script");
    std::fs::write(Path::new(&out_dir).join("corpus_sources.rs"), out)
        .expect("the generated table is written");
}
