"""Mines `crates/ply-hash/src/tests.rs` for hasher inputs and writes them as a
fixture bundle, the way `mine-checks.py` mines the checker's tests.

    python3 spikes/ply-parser/mine-hashes.py

The reference hasher's tests build most of their programs as trees rather than
as source, so what this yields is the minority written as string literals; the
bundle format, the rule that every literal is taken and none hand-picked, and
the newline convention are `mine-checks.py`'s, and its docstring is the
rationale.
"""

import importlib.util, os, sys

# Loading the sibling miner would otherwise leave a `__pycache__` beside the spike.
sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(ROOT, "crates", "ply-hash", "src", "tests.rs")
OUT = os.path.join(HERE, "fixtures", "reference-hashes.corpus")


def checks_miner():
    spec = importlib.util.spec_from_file_location("mine_checks", os.path.join(HERE, "mine-checks.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    literals = checks_miner().literals
    src = open(SRC).read()
    seen, order = set(), []
    for lit in literals(src):
        if lit not in seen:
            seen.add(lit)
            order.append(lit)
    order = [lit for lit in order if all(ch in "\n\t" or 0x20 <= ord(ch) <= 0x7E for ch in lit)]
    for lit in order:
        assert not any(line.strip() == "%%" for line in lit.split("\n")), repr(lit)
    with open(OUT, "w") as f:
        f.write(
            "Generated by spikes/ply-parser/mine-hashes.py from\n"
            "crates/ply-hash/src/tests.rs. Do not edit; regenerate.\n"
            "\n"
            "Everything above the first `%%` is this header. Below it, fixtures are\n"
            "separated by a line holding exactly `%%`, and the newline before a\n"
            "separator belongs to the separator: a fixture that ends in a newline is\n"
            "written with two, and one that does not is written with one.\n"
        )
        for lit in order:
            f.write("%%\n")
            f.write(lit)
            f.write("\n")
    print(f"{len(order)} distinct fixtures -> {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
