"""Mines `crates/ply-syntax/src/tests.rs` for parser inputs and writes them as a
fixture bundle.

    python3 spikes/ply-parser/mine-fixtures.py

Why this exists: the twenty-one real `.ply` files in the tree raise **zero**
diagnostics, so a differential over them alone says nothing at all about the
recovery half of the parser — and `docs/adr/0020-self-hosting-the-front-end.md`
§3.1 records the lexer spike's headline of 768,760 bytes later turning out to be
0.15% error paths as the thing not to repeat. The reference's own test file is
where the error paths live: every input its 200-odd tests hand to the parser,
including all 35 `errs(` call sites.

The extraction is mechanical and takes **every** Rust string literal in the
file, not a hand-picked subset. That is deliberate. A filter is a place to
quietly drop the fixture that would have gone red, and a string that is not Ply
source is still a valid differential input — both parsers must agree on it, and
disagreeing about how to recover from prose is a real disagreement. The cost is
that some fixtures are expected-output strings rather than inputs; they are
kept, counted, and not distinguished.

The bundle format is one file. Everything before the first `%%` line is a
header and is not a fixture; after that, fixtures are separated by a line
holding exactly `%%`, and **the newline immediately before a separator (or
before end of file) belongs to the separator, not to the fixture**. That last
rule is not pedantry: `errs("fn f() = \"oops")` is an unterminated string at
end of input, and a bundle that silently appended a newline would turn it into
an unterminated string before a newline, which is a different arm of
`lexer.rs`. A fixture that really does end in a newline is written with two.

Asserted at write time: no fixture contains a `%%` line, and every fixture is
printable ASCII plus newline and tab.
"""

import json, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "crates", "ply-syntax", "src", "tests.rs")
OUT = os.path.join(os.path.dirname(__file__), "fixtures", "reference-tests.corpus")

ESCAPES = {"n": "\n", "t": "\t", "r": "\r", "0": "\0", "\\": "\\", '"': '"', "'": "'"}


def literals(src: str) -> list[str]:
    """Every string literal, raw and cooked, outside line comments."""
    out, i, n = [], 0, len(src)
    while i < n:
        c = src[i]
        if c == "/" and i + 1 < n and src[i + 1] == "/":
            j = src.find("\n", i)
            i = n if j < 0 else j + 1
            continue
        if c == "r" and i + 1 < n and src[i + 1] in '#"':
            k = i + 1
            hashes = 0
            while k < n and src[k] == "#":
                hashes += 1
                k += 1
            if k < n and src[k] == '"':
                close = '"' + "#" * hashes
                j = src.find(close, k + 1)
                if j > 0:
                    out.append(src[k + 1 : j])
                    i = j + len(close)
                    continue
        if c == '"':
            j, buf = i + 1, []
            while j < n:
                if src[j] == "\\":
                    e = src[j + 1]
                    if e in ESCAPES:
                        buf.append(ESCAPES[e])
                        j += 2
                    elif e == "x":
                        buf.append(chr(int(src[j + 2 : j + 4], 16)))
                        j += 4
                    elif e == "u":
                        m = re.match(r"\{([0-9a-fA-F]+)\}", src[j + 2 :])
                        buf.append(chr(int(m.group(1), 16)))
                        j += 2 + m.end()
                    elif e == "\n":
                        # A `\` at end of line eats the newline and the indent.
                        j += 2
                        while j < n and src[j] in " \t":
                            j += 1
                    else:
                        buf.append(e)
                        j += 2
                    continue
                if src[j] == '"':
                    break
                buf.append(src[j])
                j += 1
            out.append("".join(buf))
            i = j + 1
            continue
        i += 1
    return out


def main() -> int:
    src = open(SRC).read()
    seen, order = set(), []
    for lit in literals(src):
        if lit not in seen:
            seen.add(lit)
            order.append(lit)
    for lit in order:
        assert not any(line.strip() == "%%" for line in lit.split("\n")), repr(lit)
        for ch in lit:
            assert ch in "\n\t" or 0x20 <= ord(ch) <= 0x7E, repr(lit)
    with open(OUT, "w") as f:
        f.write(
            "Generated by spikes/ply-parser/mine-fixtures.py from\n"
            "crates/ply-syntax/src/tests.rs. Do not edit; regenerate.\n"
            "\n"
            "Everything above the first `%%` is this header. Below it, fixtures are\n"
            "separated by a line holding exactly `%%`, and the newline before a\n"
            "separator belongs to the separator: a fixture that ends in a newline is\n"
            "written with two, and one that does not is written with one.\n"
        )
        for lit in order:
            f.write("%%\n")
            f.write(lit)
            f.write("\n")
    print(f"{len(order)} distinct fixtures -> {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
