[package]
name = "ply-machine-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
ply-codegen = { workspace = true }
ply-eval = { workspace = true }
ply-host = { workspace = true }
ply-machine = { workspace = true }
ply-span = { workspace = true }
ply-ty = { workspace = true }
