[package]
name = "ply-machine-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
blake3 = { workspace = true }
ply-codegen = { workspace = true }
ply-eval = { workspace = true }
ply-host = { workspace = true }
ply-launcher = { workspace = true }
ply-machine = { workspace = true }
ply-std = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
