[package]
name = "ply-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
ply-span = { workspace = true }
ply-syntax = { workspace = true }
ply-core = { workspace = true }
ply-eval = { workspace = true }
anyhow = { workspace = true }
blake3 = { workspace = true }
memchr = { workspace = true }
