[package]
name = "ply-launcher-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
ply-pack = { workspace = true }
ctor = { workspace = true }
ply-codegen = { workspace = true }
ply-eval = { workspace = true }
ply-launcher = { workspace = true }
ply-machine = { workspace = true }
tempfile = { workspace = true }
