[package]
name = "ply-store-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
ply-span = { workspace = true }
ply-syntax = { workspace = true }
ply-core = { workspace = true }
ply-hash = { workspace = true }
ply-store = { workspace = true }
blake3 = { workspace = true }
