//! The comparison this spike exists for: for every `.ply` file in the tree, the
//! Ply lexer's token stream against `crates/ply-syntax`'s.
//!
//! It shells out to the shipping `ply` binary rather than driving `ply-eval` in
//! process, because the shipping binary is what a user would run and because
//! the 10,000-nested-call bound this lexer is shaped around is the one the CLI
//! installs. Driving the evaluator directly would let the harness choose a
//! bound no user can choose.
//!
//! Nothing here skips. If the `ply` binary is missing the tests fail and say
//! how to build it; `CONTRIBUTING.md` §"The suite proves less than it looks
//! like it proves" is about four gates that skip silently and this is not going
//! to be a fifth.

use ply_lexer_spike_harness::{byte_literal, floats_to_bits, records, reference_dump};
use std::path::{Path, PathBuf};
use std::process::Command;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("the harness sits at <root>/spikes/ply-lexer/harness")
        .to_path_buf()
}

/// The shipping binary, release first because `examples/desk.ply` is 160
/// kilobytes and the debug interpreter is about eight times slower on it.
fn ply_binary() -> PathBuf {
    if let Ok(explicit) = std::env::var("PLY_BIN") {
        let path = PathBuf::from(explicit);
        assert!(
            path.exists(),
            "PLY_BIN names {}, which does not exist",
            path.display()
        );
        return path;
    }
    let root = repo_root();
    for profile in ["release", "debug"] {
        let candidate = root.join("target").join(profile).join("ply");
        if candidate.exists() {
            return candidate;
        }
    }
    panic!(
        "no `ply` binary at {}/target/{{release,debug}}/ply — run `cargo build -p ply-cli --bin ply` \
         (or `--release`) first, or set PLY_BIN",
        root.display()
    );
}

fn spike_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the harness sits inside the spike")
        .to_path_buf()
}

/// Run the Ply lexer over `bytes` and return its dump.
///
/// The source arrives as a `b"..."` literal because there is no other way in:
/// Ply has no file-reading host handler, so a program either holds its input as
/// a literal or never sees it.
fn ply_dump(bytes: &[u8], label: &str) -> String {
    // A counter as well as the label: two tests may lex the same fixture, and
    // `cargo test` runs them on different threads at the same time.
    static NEXT: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let dir = std::env::temp_dir().join(format!(
        "ply-lexer-spike-{}-{}-{}",
        std::process::id(),
        NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed),
        label.replace(['/', '.'], "_")
    ));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("a temp directory");
    std::fs::copy(spike_dir().join("lexer.ply"), dir.join("lexer.ply")).expect("copy the lexer");
    std::fs::write(
        dir.join("probe.ply"),
        format!(
            "// Generated by spikes/ply-lexer/harness/tests/agreement.rs. Not checked in.\n\
             import lexer (dump)\n\n\
             fn source() -> Bytes = {}\n\n\
             fn main() -> String = dump(source())\n",
            byte_literal(bytes)
        ),
    )
    .expect("write the probe");

    let out = Command::new(ply_binary())
        .arg("run")
        .arg(&dir)
        .arg("--json")
        .output()
        .expect("run ply");
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
    assert!(
        out.status.success(),
        "`ply run {}` failed ({}):\n{stdout}\n{stderr}",
        dir.display(),
        out.status
    );
    let dump = extract_value(&stdout, &dir);
    let _ = std::fs::remove_dir_all(&dir);
    dump
}

/// The `value` field of `ply run --json`, unwrapped.
///
/// Two layers of quoting, and both are load-bearing. `ply run` puts
/// `Value::to_string()` in that field, and a `Value::Str` *renders* with its
/// own quotes and its own escaping (`ply_eval::value::escape`), so the JSON
/// string holds `"<dump>"` and serde escapes those two quotes again. What
/// arrives is therefore `\"<dump>\"` between the JSON quotes.
///
/// The dump is printable ASCII with no `"` and no `\` by construction — the
/// harness's own `the_dump_is_printable_ascii_with_no_quote_and_no_backslash`
/// asserts that of the reference side — so between those two markers the dump
/// is verbatim and no unescaper is needed. If either assumption ever breaks
/// this fails loudly rather than quietly comparing an unescaper against a
/// lexer.
fn extract_value(stdout: &str, dir: &Path) -> String {
    let needle = "\n  \"value\": \"";
    let occurrences = stdout.matches(needle).count();
    assert_eq!(
        occurrences,
        1,
        "`ply run {}` printed {occurrences} top-level `value` fields:\n{stdout}",
        dir.display()
    );
    let after = &stdout[stdout.find(needle).expect("checked above") + needle.len()..];
    let quote = "\\\"";
    assert!(
        after.starts_with(quote),
        "`ply run {}` answered with something that is not a rendered `String`; \
         the entry point must return one:\n{stdout}",
        dir.display()
    );
    let rest = &after[quote.len()..];
    let end = rest
        .find(quote)
        .unwrap_or_else(|| panic!("the rendered `String` is never closed in:\n{stdout}"));
    let body = &rest[..end];
    assert!(
        !body.contains('\\') && !body.contains('"'),
        "the Ply dump holds a character `ply run --json` escapes, so it is not the \
         printable-ASCII form the comparison assumes:\n{body}"
    );
    body.to_string()
}

/// The first record the two dumps disagree on, with context, or `None`.
fn first_difference(reference: &str, actual: &str) -> Option<String> {
    let want = records(reference);
    let got = records(actual);
    for i in 0..want.len().max(got.len()) {
        let a = want.get(i).copied();
        let b = got.get(i).copied();
        if a != b {
            let from = i.saturating_sub(3);
            let mut report = format!("record {i} of {} differs\n", want.len());
            report.push_str(&format!(
                "  rust: {a:?}\n  ply : {b:?}\n  context (rust):\n"
            ));
            for (j, r) in want.iter().enumerate().skip(from).take(8) {
                report.push_str(&format!("    {j:>6} {r}\n"));
            }
            report.push_str("  context (ply):\n");
            for (j, r) in got.iter().enumerate().skip(from).take(8) {
                report.push_str(&format!("    {j:>6} {r}\n"));
            }
            return Some(report);
        }
    }
    None
}

fn check_agreement(path: &Path) {
    let began = std::time::Instant::now();
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let text = String::from_utf8(bytes.clone())
        .unwrap_or_else(|e| panic!("{} is not UTF-8: {e}", path.display()));
    let reference = reference_dump(&text);
    let label = path.file_name().unwrap().to_string_lossy().to_string();
    let actual = floats_to_bits(&ply_dump(&bytes, &label));
    if let Some(diff) = first_difference(&reference, &actual) {
        panic!(
            "the Ply lexer and `ply_syntax::lexer` disagree on {}:\n{diff}",
            path.display()
        );
    }
    // Printed under `--nocapture` so that a file the loop silently skipped is
    // visible: a comparison over an empty corpus passes.
    println!(
        "  agreed {:>52}  {:>7} bytes  {:>6} records  {:>7.2}s",
        path.display()
            .to_string()
            .rsplit('/')
            .take(2)
            .collect::<Vec<_>>()
            .join("/"),
        bytes.len(),
        records(&reference).len(),
        began.elapsed().as_secs_f64()
    );
}

fn ply_files(dir: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .map(|e| e.expect("a directory entry").path())
        .filter(|p| p.extension().is_some_and(|e| e == "ply"))
        .collect();
    out.sort();
    assert!(!out.is_empty(), "{} holds no .ply files", dir.display());
    out
}

#[test]
fn the_ply_lexer_agrees_with_the_rust_one_on_every_example() {
    for path in ply_files(&repo_root().join("examples")) {
        check_agreement(&path);
    }
}

#[test]
fn the_ply_lexer_agrees_with_the_rust_one_on_the_kernel_benchmarks() {
    for path in ply_files(&repo_root().join("benches").join("kernel")) {
        check_agreement(&path);
    }
}

#[test]
fn the_ply_lexer_agrees_with_the_rust_one_on_the_shipped_standard_library() {
    for path in ply_files(&repo_root().join("crates").join("ply-std").join("ply")) {
        check_agreement(&path);
    }
}

/// Nothing in the corpus above reaches a malformed literal, an out-of-range
/// number, or an unterminated string, so agreeing on it says nothing at all
/// about the error paths, which are half of what `lexer.rs` does. These ten
/// files are the only thing in the spike that exercises them: **all 25
/// diagnostics in the whole comparison come from five of these ten fixtures**,
/// and the 767,638 bytes of real source raise none.
///
/// > **Corrected (verification pass, 2026-08-24).** This doc opened: *"The
/// > corpus above is every `.ply` file in the tree and **all of it is ASCII** —
/// > checked, and the reason this test exists."* Both halves are false, and the
/// > second is refuted by
/// > `every_non_ascii_byte_in_the_corpus_is_somewhere_both_lexers_agree`
/// > forty lines below, which asserts **1,543** non-ASCII bytes and carries two
/// > correction blocks of its own saying so. The corpus is **33** files; the
/// > tree holds **109** `.ply` files outside `spikes/`, so **86** files and
/// > **95,419** bytes are not compared — among them
/// > `tests/fixtures/unterminated_string.ply`, the one file outside this spike
/// > that raises a lexer diagnostic. (Compared by hand during the verification
/// > pass: the two lexers agree on it exactly, `E0002` included.) A stale
/// > sentence sitting above a test whose own body refutes it is this
/// > repository's signature defect in miniature.
#[test]
fn the_ply_lexer_agrees_with_the_rust_one_on_the_hand_written_edge_cases() {
    for path in ply_files(&spike_dir().join("fixtures")) {
        check_agreement(&path);
    }
}

/// Where the corpus's non-ASCII bytes are, which is the whole reason the four
/// tests above can agree at all.
///
/// > **Corrected.** This test used to assert that every file it reads is
/// > ASCII, on the strength of a `grep -c $'[\x80-\xff]'` that reported `0`
/// > for every file and was simply not working. There are **1,543** non-ASCII
/// > bytes in the corpus — em dashes and section signs in prose comments. The
/// > agreement is real; the reason for it was not what the first version of
/// > this test said.
///
/// > **Corrected again, by running it.** The replacement asserted that every
/// > non-ASCII byte falls *outside every token span*. It does not:
/// > `examples/hello.ply` holds three accented characters inside a string
/// > literal at offset 17,656. Two claims about this corpus in a row, both
/// > written from a tool that was not doing what it looked like it was doing,
/// > both refuted by the check that was supposed to confirm them.
///
/// What is actually true: every non-ASCII byte in the corpus is either trivia
/// or inside a `Str` literal, and those are exactly the two positions where the
/// two lexers agree — trivia is skipped by both, and a string's bytes are
/// copied through by both, which
/// `a_non_ascii_character_inside_a_string_is_not_a_divergence` pins. Not one of
/// them sits at a token's **first** byte, which is the only place the two
/// disagree. So this corpus does not exercise the divergence, and
/// `the_two_lexers_differ_on_a_unicode_identifier` and its two neighbours are
/// what cover it.
#[test]
fn every_non_ascii_byte_in_the_corpus_is_somewhere_both_lexers_agree() {
    let mut non_ascii = 0usize;
    let mut in_string = 0usize;
    let mut files = 0usize;
    for dir in corpus_dirs() {
        for path in ply_files(&dir) {
            let bytes = std::fs::read(&path).expect("readable");
            let text = String::from_utf8(bytes.clone()).expect("UTF-8");
            let (tokens, _) = ply_syntax::lexer::lex(ply_span::SourceId(0), &text);
            files += 1;
            for (at, _) in bytes.iter().enumerate().filter(|(_, b)| **b >= 0x80) {
                non_ascii += 1;
                let covering = tokens
                    .iter()
                    .find(|t| (t.span.start as usize) <= at && at < (t.span.end as usize));
                match covering.map(|t| &t.kind) {
                    None => {}
                    Some(ply_syntax::lexer::TokenKind::Str(_)) => in_string += 1,
                    Some(other) => panic!(
                        "{} has a non-ASCII byte at offset {at} inside the token {other:?}. \
                         Every non-ASCII byte in this corpus is trivia or a string's \
                         contents, which is why the agreement tests pass over it; one \
                         anywhere else is a position where the Ply lexer answers \
                         differently on purpose, so the agreement claim has to be \
                         re-decided. README, Where this disagrees on purpose.",
                        path.display()
                    ),
                }
            }
        }
    }
    assert!(files >= 20, "only {files} files were checked");
    // Pinned so that a corpus that lost its prose — or gained a file this loop
    // silently skipped — is visible rather than quietly narrowing the claim.
    assert_eq!(
        (non_ascii, in_string),
        (1543, 45),
        "the corpus holds {non_ascii} non-ASCII bytes of which {in_string} are inside string \
         literals, not the 1,543 and 45 this was written against"
    );
}

fn corpus_dirs() -> Vec<PathBuf> {
    vec![
        repo_root().join("examples"),
        repo_root().join("benches").join("kernel"),
        repo_root().join("crates").join("ply-std").join("ply"),
        spike_dir().join("fixtures"),
    ]
}

// --- Where the two lexers disagree on purpose --------------------------------
//
// Three shapes, all at the first byte of a token, all because `lexer.rs` asks
// `char::is_alphabetic` and `char::is_whitespace` there and Ply has no
// character type and no Unicode table to ask. Asserted as exact dumps rather
// than described, so that a change to either lexer that closes or widens a
// divergence fails here instead of being discovered by a user.

fn both_dumps(text: &str, label: &str) -> (String, String) {
    let bytes = text.as_bytes();
    (
        reference_dump(text),
        floats_to_bits(&ply_dump(bytes, label)),
    )
}

/// The one divergence that changes the **token stream** rather than only a
/// diagnostic: `lexer.rs` accepts any `char::is_alphabetic` as an identifier.
#[test]
fn the_two_lexers_differ_on_a_unicode_identifier() {
    let (rust, ply) = both_dumps("let \u{e9} = 1\n", "div-ident");
    assert_eq!(rust, "0:3:k:let;4:6:i:\u{e9};7:8:p:eq;9:10:n:1;11:11:e;");
    assert_eq!(ply, "0:3:k:let;7:8:p:eq;9:10:n:1;11:11:e;4:6:!:X0001;");
}

/// `char::is_whitespace` accepts sixteen characters outside ASCII. This one is
/// worse than it looks: the Rust lexer skips a non-breaking space silently, so
/// the source that produced it is *accepted*, and the Ply lexer refuses it.
#[test]
fn the_two_lexers_differ_on_a_unicode_space() {
    let (rust, ply) = both_dumps("a\u{a0}b\n", "div-space");
    assert_eq!(rust, "0:1:i:a;3:4:i:b;5:5:e;");
    assert_eq!(ply, "0:1:i:a;3:4:i:b;5:5:e;1:3:!:X0001;");
}

/// The mildest of the three: both refuse, at the same span, with no token. Only
/// the diagnostic code differs, because the Ply lexer cannot tell this case
/// from the identifier case and says so with a code of its own.
#[test]
fn the_two_lexers_differ_only_in_the_code_on_a_unicode_symbol() {
    for (text, label) in [
        ("a \u{20ac} b\n", "div-euro"),
        ("a \u{2014} b\n", "div-dash"),
    ] {
        let (rust, ply) = both_dumps(text, label);
        assert_eq!(rust, "0:1:i:a;6:7:i:b;8:8:e;2:5:!:E0001;");
        assert_eq!(ply, "0:1:i:a;6:7:i:b;8:8:e;2:5:!:X0001;");
        assert_eq!(
            rust.replace("E0001", "X0001"),
            ply,
            "the two differ in more than the diagnostic code"
        );
    }
}

// The four shapes that look like they should diverge and do not. Each was
// written down as a divergence first and refuted by running it.

#[test]
fn a_backslash_before_a_non_ascii_character_is_not_a_divergence() {
    let (rust, ply) = both_dumps("\"a\\\u{e9}b\"\n", "same-escape");
    assert_eq!(rust, "0:7:s:61c3a962;8:8:e;2:5:!:E0001;");
    assert_eq!(ply, rust);
}

#[test]
fn a_non_ascii_character_inside_a_byte_literal_is_not_a_divergence() {
    let (rust, ply) = both_dumps("b\"a\u{e9}b\"\n", "same-bytes");
    assert_eq!(rust, "0:7:b:6162;8:8:e;3:5:!:E0001;");
    assert_eq!(ply, rust);
}

#[test]
fn a_non_ascii_character_inside_a_string_is_not_a_divergence() {
    let (rust, ply) = both_dumps("\"caf\u{e9}\"\n", "same-string");
    assert_eq!(rust, "0:7:s:636166c3a9;8:8:e;");
    assert_eq!(ply, rust);
}

#[test]
fn a_non_ascii_character_inside_a_comment_is_not_a_divergence() {
    let (rust, ply) = both_dumps("// caf\u{e9}\n1\n", "same-comment");
    assert_eq!(rust, "9:10:n:1;11:11:e;");
    assert_eq!(ply, rust);
}

// --- Whether the comparison can fail ----------------------------------------
//
// Everything above is a green result, and a green result over a comparison that
// cannot go red is the defect this repository names first. These five mutate a
// dump that really did come out of the Ply lexer, in the five ways a
// same-shaped-but-wrong lexer would differ, and assert the comparator says so.
// Four of them are the hazards a survey of `std.json`'s parser flagged as the
// ways a token-stream comparison is usually blind: kind, payload, span, a
// dropped token, and a dropped diagnostic.

/// A fixture that has all five things to break: tokens, a payload, spans, and
/// diagnostics.
fn a_mutable_dump() -> (String, String) {
    let path = spike_dir().join("fixtures").join("bytes.ply");
    let bytes = std::fs::read(&path).expect("the fixture");
    let text = String::from_utf8(bytes.clone()).expect("ASCII");
    let reference = reference_dump(&text);
    let actual = floats_to_bits(&ply_dump(&bytes, "mutation"));
    assert!(
        first_difference(&reference, &actual).is_none(),
        "the fixture must agree before it can be mutated"
    );
    (reference, actual)
}

#[test]
fn the_comparison_notices_a_token_whose_kind_is_wrong() {
    let (reference, actual) = a_mutable_dump();
    let mutated = actual.replacen(":n:7;", ":i:7;", 1);
    assert_ne!(mutated, actual, "the mutation did not apply");
    assert!(first_difference(&reference, &mutated).is_some());
}

#[test]
fn the_comparison_notices_a_token_whose_payload_is_wrong() {
    let (reference, actual) = a_mutable_dump();
    let mutated = actual.replacen("b:47455420", "b:47455421", 1);
    assert_ne!(mutated, actual, "the mutation did not apply");
    assert!(first_difference(&reference, &mutated).is_some());
}

/// The hazard worth naming: a lexer with every kind and payload right and every
/// offset wrong would agree with a span-blind comparator perfectly.
#[test]
fn the_comparison_notices_a_token_whose_span_is_wrong() {
    let (reference, actual) = a_mutable_dump();
    let mutated = actual.replacen("4:11:b:", "4:12:b:", 1);
    assert_ne!(mutated, actual, "the mutation did not apply");
    assert!(first_difference(&reference, &mutated).is_some());
}

/// A zip that stops at the shorter of the two would swallow this.
#[test]
fn the_comparison_notices_a_token_that_is_missing_from_the_end() {
    let (reference, actual) = a_mutable_dump();
    let records: Vec<&str> = records(&actual);
    let mutated: String = records[..records.len() - 1]
        .iter()
        .map(|r| format!("{r};"))
        .collect();
    assert!(first_difference(&reference, &mutated).is_some());
}

/// `lex` never fails — it answers with diagnostics *beside* the tokens — so a
/// comparison of tokens alone passes a lexer that silently accepts malformed
/// input.
#[test]
fn the_comparison_notices_a_diagnostic_that_was_not_raised() {
    let (reference, actual) = a_mutable_dump();
    let mutated = actual.replacen("42:44:!:E0001;", "", 1);
    assert_ne!(mutated, actual, "the mutation did not apply");
    assert!(first_difference(&reference, &mutated).is_some());
}

/// And the whole apparatus, end to end: if the Ply lexer itself is wrong, the
/// agreement tests go red rather than the harness quietly agreeing with itself.
#[test]
fn a_broken_ply_lexer_makes_the_agreement_tests_fail() {
    let source = std::fs::read_to_string(spike_dir().join("lexer.ply")).expect("the lexer");
    // `++` is `plusplus`; a lexer that forgot maximal munch would call it two
    // `plus` tokens. One character, in one string literal, in `punct`.
    let broken = source.replacen("b\"plusplus\", b\"plus\"", "b\"plus\", b\"plus\"", 1);
    assert_ne!(broken, source, "the mutation did not apply to lexer.ply");

    let dir = std::env::temp_dir().join(format!(
        "ply-lexer-spike-broken-{}-{:?}",
        std::process::id(),
        std::thread::current().id()
    ));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("a temp directory");
    std::fs::write(dir.join("lexer.ply"), &broken).expect("write the broken lexer");
    std::fs::write(
        dir.join("probe.ply"),
        "import lexer (dump)\nfn main() -> String = dump(b\"a ++ b\")\n",
    )
    .expect("write the probe");
    let out = Command::new(ply_binary())
        .arg("run")
        .arg(&dir)
        .arg("--json")
        .output()
        .expect("run ply");
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let mutated = extract_value(&String::from_utf8_lossy(&out.stdout), &dir);
    let _ = std::fs::remove_dir_all(&dir);

    let reference = reference_dump("a ++ b");
    assert!(
        first_difference(&reference, &mutated).is_some(),
        "a lexer that lexes `++` as `plus` agreed with the reference:\n{mutated}"
    );
}
