[package]
name = "ply-prove"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ply-span = { workspace = true }
ply-syntax = { workspace = true }
ply-core = { workspace = true }
ply-hash = { workspace = true }
ply-eval = { workspace = true }
blake3 = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
stacker = { workspace = true }
