//! What the store stamps are a function of: the modules a root reaches by its imports, and the
//! `Cargo.lock` entries the runtime's crates reach.

use ply_launcher::code::{Shelf, closure, lock_closure};
use std::path::{Path, PathBuf};

fn write(path: &Path, text: &str) {
    std::fs::create_dir_all(path.parent().expect("a file is in a directory")).expect("mkdir");
    std::fs::write(path, text).expect("write");
}

/// A shelf, and two packages: `cli`, which depends on `dep` by path, and `dep`.
fn repository() -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("a scratch directory");
    let r = dir.path();
    write(
        &r.join("std/json.ply"),
        "import std.bytes\npub fn j() -> Int = 1\n",
    );
    write(&r.join("std/bytes.ply"), "pub fn b() -> Int = 1\n");
    write(&r.join("std/net.ply"), "pub fn n() -> Int = 1\n");
    write(
        &r.join("compiler/front.ply"),
        "import spine (s)\npub fn f() -> Int = 1\n",
    );
    write(&r.join("compiler/spine.ply"), "pub fn s() -> Int = 1\n");
    write(&r.join("compiler/emit.ply"), "pub fn e() -> Int = 1\n");
    write(
        &r.join("cli/ply.pkg"),
        "fn package() -> Manifest = { dependencies: [{ source: Path(\"../dep\") }] }\n",
    );
    write(
        &r.join("cli/tests.ply"),
        "import results\nimport std.json (j)\nimport suite.decide (d)\n",
    );
    write(&r.join("cli/results.ply"), "import compiler.front (f)\n");
    write(&r.join("cli/fmt.ply"), "import std.net\n");
    write(
        &r.join("dep/ply.pkg"),
        "fn package() -> Manifest = { dependencies: [] }\n",
    );
    write(&r.join("dep/decide.ply"), "pub fn d() -> Int = 1\n");
    write(&r.join("dep/keys.ply"), "pub fn k() -> Int = 1\n");
    dir
}

fn named(root: &Path, files: Vec<PathBuf>) -> Vec<String> {
    files
        .iter()
        .map(|f| {
            f.strip_prefix(root)
                .expect("inside the repository")
                .to_string_lossy()
                .into_owned()
        })
        .collect()
}

/// A dependency is reached whole, since which of its modules an import names is the manifest's to
/// say; a module of the root's own package, or of the shelf, only when an import reaches it.
#[test]
fn a_root_reaches_what_it_imports_and_nothing_else() {
    let repo = repository();
    let r = repo.path();
    let (std_dir, compiler_dir) = (r.join("std"), r.join("compiler"));
    let shelf = Shelf {
        std: &std_dir,
        compiler: &compiler_dir,
    };
    assert_eq!(
        named(r, closure(&shelf, &r.join("cli"), &["tests"])),
        [
            "cli/ply.pkg",
            "cli/results.ply",
            "cli/tests.ply",
            "compiler/front.ply",
            "compiler/spine.ply",
            "dep/decide.ply",
            "dep/keys.ply",
            "dep/ply.pkg",
            "std/bytes.ply",
            "std/json.ply",
        ]
    );
}

/// An import that resolves to nothing would leave code out of the stamp, so it stops the build.
#[test]
#[should_panic(expected = "names no module of its package")]
fn an_import_that_names_nothing_stops_the_build() {
    let repo = repository();
    let r = repo.path();
    write(
        &r.join("lone/ply.pkg"),
        "fn package() -> Manifest = { dependencies: [] }\n",
    );
    write(&r.join("lone/main.ply"), "import missing (m)\n");
    let (std_dir, compiler_dir) = (r.join("std"), r.join("compiler"));
    let shelf = Shelf {
        std: &std_dir,
        compiler: &compiler_dir,
    };
    closure(&shelf, &r.join("lone"), &["main"]);
}

const LOCK: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "a"
version = "0.1.0"
dependencies = [
 "b",
 "c 1.0.0",
]

[[package]]
name = "b"
version = "0.1.0"

[[package]]
name = "c"
version = "1.0.0"

[[package]]
name = "c"
version = "2.0.0"
checksum = "two"

[[package]]
name = "unrelated"
version = "0.1.0"
dependencies = [
 "c 2.0.0",
]
"#;

/// A crate the runtime does not build on, or another version of one it does, moves nothing.
#[test]
fn the_runtime_reaches_its_own_entries_of_the_lock_and_no_others() {
    let reached = lock_closure(LOCK, &["a"]);
    assert!(reached.contains("name = \"a\"") && reached.contains("name = \"b\""));
    assert!(reached.contains("version = \"1.0.0\""), "{reached}");
    assert!(!reached.contains("checksum = \"two\""), "{reached}");
    assert!(!reached.contains("unrelated"), "{reached}");
}
