//! What the runtime's stamp is a function of beyond its crates' sources: the `Cargo.lock` entries
//! they reach.

use ply_launcher::code::lock_closure;

const LOCK: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "a"
version = "0.1.0"
dependencies = [
 "b",
 "c 1.0.0",
]

[[package]]
name = "b"
version = "0.1.0"

[[package]]
name = "c"
version = "1.0.0"

[[package]]
name = "c"
version = "2.0.0"
checksum = "two"

[[package]]
name = "unrelated"
version = "0.1.0"
dependencies = [
 "c 2.0.0",
]
"#;

/// A crate the runtime does not build on, or another version of one it does, moves nothing.
#[test]
fn the_runtime_reaches_its_own_entries_of_the_lock_and_no_others() {
    let reached = lock_closure(LOCK, &["a"]);
    assert!(reached.contains("name = \"a\"") && reached.contains("name = \"b\""));
    assert!(reached.contains("version = \"1.0.0\""), "{reached}");
    assert!(!reached.contains("checksum = \"two\""), "{reached}");
    assert!(!reached.contains("unrelated"), "{reached}");
}
