[package]
name = "ply-test-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
ply-eval = { workspace = true }
ply-codegen = { workspace = true }
ply-store = { workspace = true }
ply-test = { workspace = true }
blake3 = { workspace = true }
