[package]
name = "ply-eval-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
ply-eval = { workspace = true }
ply-codegen = { workspace = true }
blake3 = { workspace = true }
rpds = { workspace = true }
rust_decimal = { workspace = true }
serde_json = { workspace = true }
