//! The fifth differential: `derive.ply` against `crates/ply-derive`. Every module is expanded on
//! its own, and the source each derivation generates is compared byte for byte, with the
//! diagnostics expansion raises.

use ply_parser_spike_harness::reference_derive_dump;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("the harness sits three levels under the repository root")
        .to_path_buf()
}

fn spike_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the harness sits inside the spike")
        .to_path_buf()
}

fn ply_binary() -> PathBuf {
    if let Ok(explicit) = std::env::var("PLY_BIN") {
        return PathBuf::from(explicit);
    }
    let root = repo_root();
    for profile in ["release", "debug"] {
        let candidate = root.join("target").join(profile).join("ply");
        if candidate.exists() {
            return candidate;
        }
    }
    panic!("no `ply` binary; build one or set PLY_BIN");
}

fn source_dir() -> PathBuf {
    match std::env::var("PLY_PARSER_SRC") {
        Ok(d) => PathBuf::from(d),
        Err(_) => spike_dir(),
    }
}

const MODULES: [&str; 9] = [
    "lexer.ply",
    "spine.ply",
    "types.ply",
    "patterns.ply",
    "exprs.ply",
    "items.ply",
    "rewrite.ply",
    "resolve.ply",
    "derive.ply",
];

struct Project(PathBuf);

impl Project {
    fn new() -> Project {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "ply-derive-spike-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("a temp directory");
        for m in MODULES {
            std::fs::copy(source_dir().join(m), dir.join(m))
                .unwrap_or_else(|e| panic!("copying {m}: {e}"));
        }
        Project(dir)
    }

    /// One `ply run` for many inputs, each a list of `(name, source)` modules.
    fn dumps(&self, inputs: &[Vec<(String, String)>]) -> Vec<String> {
        let mut src = String::from(
            "// Generated by spikes/ply-parser/harness/tests/derive.rs. Not checked in.\n\
             import derive (derive_dump)\n",
        );
        let mut parts: Vec<String> = Vec::new();
        for (i, modules) in inputs.iter().enumerate() {
            let mut entries: Vec<String> = Vec::new();
            for (j, (name, text)) in modules.iter().enumerate() {
                src.push_str(&format!(
                    "fn n{i}_{j}() -> Bytes = {}\nfn s{i}_{j}() -> Bytes = {}\n",
                    byte_literal(name.as_bytes()),
                    byte_literal(text.as_bytes())
                ));
                entries.push(format!("{{ name: n{i}_{j}(), src: s{i}_{j}() }}"));
            }
            src.push_str(&format!(
                "fn p{i}() -> String = derive_dump([{}])\n",
                entries.join(", ")
            ));
            parts.push(format!("bytes_of_string(p{i}())"));
            parts.push("b\"\\x01\"".to_string());
        }
        src.push_str(&format!(
            "fn main() -> String = string_of_bytes(bytes_concat_all([{}]))\n",
            parts.join(", ")
        ));
        std::fs::write(self.0.join("probe.ply"), src).expect("write the probe");
        let _ = std::fs::remove_dir_all(self.0.join(".ply-cache"));
        let out = Command::new(ply_binary())
            .args(["run", "--json"])
            .args(backend_args())
            .arg(&self.0)
            .output()
            .expect("run ply");
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        assert!(
            out.status.success(),
            "`ply run {}` failed ({}):\n{stdout}\n{stderr}",
            self.0.display(),
            out.status
        );
        let joined = extract_value(&stdout);
        let mut parts: Vec<String> = joined.split('\u{1}').map(str::to_string).collect();
        let last = parts.pop().expect("split yields at least one part");
        assert!(
            last.is_empty() && parts.len() == inputs.len(),
            "the probe answered {} dumps for {} inputs",
            parts.len(),
            inputs.len()
        );
        parts
    }
}

impl Drop for Project {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// The rendered `String` out of `ply run --json`, its two escaping layers undone: a generated
/// source holds quotes, backslashes and newlines, all of which cross both.
fn extract_value(stdout: &str) -> String {
    let needle = "\n  \"value\": \"";
    let at = stdout
        .find(needle)
        .unwrap_or_else(|| panic!("no `value` field in:\n{stdout}"));
    let after = &stdout[at + needle.len()..];
    let quote = "\\\"";
    assert!(
        after.starts_with(quote),
        "not a rendered `String`:\n{stdout}"
    );
    // The outer layer is the JSON string: it ends at the first quote no backslash escapes.
    let end = find_json_string_end(after);
    let once = unescape_json(&after[..end]);
    // What remains is the interpreter's own rendering of a `String`, quoted and escaped once more.
    let inner = once
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or_else(|| panic!("not a rendered `String`: {once}"));
    unescape_json(inner)
}

fn find_json_string_end(s: &str) -> usize {
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => i += 2,
            b'"' => return i,
            _ => i += 1,
        }
    }
    panic!("the JSON string is not closed");
}

fn unescape_json(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match chars.next() {
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some('"') => out.push('"'),
            Some('\\') => out.push('\\'),
            Some('u') => {
                let hex: String = chars.by_ref().take(4).collect();
                let code = u32::from_str_radix(&hex, 16).expect("a \\u escape");
                out.push(char::from_u32(code).expect("a scalar"));
            }
            Some(other) => {
                out.push('\\');
                out.push(other);
            }
            None => out.push('\\'),
        }
    }
    out
}

fn byte_literal(bytes: &[u8]) -> String {
    let mut s = String::from("b\"");
    for &b in bytes {
        match b {
            b'"' => s.push_str("\\\""),
            b'\\' => s.push_str("\\\\"),
            b'\n' => s.push_str("\\n"),
            b'\t' => s.push_str("\\t"),
            b'\r' => s.push_str("\\r"),
            0x20..=0x7e => s.push(b as char),
            _ => s.push_str(&format!("\\x{b:02x}")),
        }
    }
    s.push('"');
    s
}

fn first_difference(reference: &str, actual: &str) -> Option<String> {
    if reference == actual {
        return None;
    }
    let at = reference
        .bytes()
        .zip(actual.bytes())
        .position(|(a, b)| a != b)
        .unwrap_or(reference.len().min(actual.len()));
    let from = at.saturating_sub(80);
    let window = |s: &str| {
        let end = (at + 120).min(s.len());
        s.get(from..end).unwrap_or("").to_string()
    };
    Some(format!(
        "differs at byte {at} of {} (rust) / {} (ply)\n  rust: ...{}...\n  ply : ...{}...",
        reference.len(),
        actual.len(),
        window(reference),
        window(actual)
    ))
}

fn compare(label: &str, inputs: &[(String, Vec<(String, String)>)]) {
    let project = Project::new();
    let programs: Vec<Vec<(String, String)>> = inputs.iter().map(|(_, p)| p.clone()).collect();
    let got = project.dumps(&programs);
    let mut failures: Vec<String> = Vec::new();
    let mut generated = 0usize;
    for ((name, program), actual) in inputs.iter().zip(&got) {
        let reference = reference_derive_dump(program);
        generated += reference.matches("S;").count();
        if let Some(report) = first_difference(&reference, actual) {
            failures.push(format!(
                "{label}: the two derivers disagree on {name}:\n{report}"
            ));
        }
    }
    println!(
        "  {label}: {} module(s), {generated} generated definition(s) agree",
        inputs.len() - failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} of {} modules disagree\n\n{}",
        failures.len(),
        inputs.len(),
        failures.join("\n")
    );
}

fn ply_files(dir: &Path, prefix: &str) -> Vec<(String, String)> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "ply"))
        .collect();
    files.sort();
    files
        .into_iter()
        .map(|p| {
            let stem = p.file_stem().unwrap().to_string_lossy().to_string();
            (
                format!("{prefix}{stem}"),
                std::fs::read_to_string(&p).expect("UTF-8"),
            )
        })
        .collect()
}

#[test]
fn the_ply_deriver_agrees_with_ply_derive_on_the_hand_written_modules() {
    let text = std::fs::read_to_string(spike_dir().join("fixtures/derive-programs.corpus"))
        .expect("the hand-written derive modules");
    let inputs: Vec<(String, Vec<(String, String)>)> = ply_parser_spike_harness::bundle(&text)
        .into_iter()
        .enumerate()
        .map(|(i, f)| {
            (
                format!("derive-programs.corpus#{i}"),
                vec![("t".to_string(), f)],
            )
        })
        .collect();
    assert!(
        !inputs.is_empty(),
        "the hand-written bundle holds no module"
    );
    compare("hand-written modules", &inputs);
}

#[test]
fn the_ply_deriver_agrees_with_ply_derive_on_every_example_and_the_standard_library() {
    let mut inputs: Vec<(String, Vec<(String, String)>)> = Vec::new();
    for (name, text) in ply_files(&repo_root().join("examples"), "examples/") {
        inputs.push((name.clone(), vec![(name, text)]));
    }
    for (name, text) in ply_files(&repo_root().join("crates/ply-std/ply"), "std.") {
        inputs.push((name.clone(), vec![(name, text)]));
    }
    compare("examples and std", &inputs);
}

/// `--backend` for every `ply` the differential runs: `cranelift` unless `PLY_BACKEND` names
/// another, or `none` for the interpreter alone.
fn backend_args() -> Vec<String> {
    match std::env::var("PLY_BACKEND").as_deref() {
        Ok("none") => Vec::new(),
        Ok(other) => vec!["--backend".to_string(), other.to_string()],
        Err(_) => vec!["--backend".to_string(), "cranelift".to_string()],
    }
}
