//! The eighth comparison: `emit.ply` against `crates/ply-codegen`'s C emitter.
//!
//! The stage the goal names. `lower_diff.rs` says whether a Ply implementation builds the tree a
//! code generator reads; this says whether it writes the C a code generator writes -- byte for
//! byte, placeholders and all.
//!
//! **A nested binary is not in the corpus, and the reason is a finding rather than a gap.** For
//! `a * b + c` the reference emits
//!
//! ```text
//! t1 = unbox(a); t2 = unbox(b); t3 = unbox(c); t4 = mul(t1,t2); t5 = add(t4,t3)
//! ```
//!
//! and this port emits
//!
//! ```text
//! t1 = unbox(a); t2 = unbox(b); t3 = mul(t1,t2); t4 = unbox(c); t5 = add(t3,t4)
//! ```
//!
//! Same arithmetic, same answer, different order: the reference unboxes every operand of the
//! *outer* node before the inner node's arithmetic runs.
//!
//! **It is not the emitter, and the first note here said it was.** Two things settle that.
//! `reference_lower_dump` on the same function is
//! `bbin(add,bbin(mul,ovar(a,0),ovar(b,1)),ovar(c,2))` -- the tree this port lowers, so the two
//! agree on the input. And `c/emit.rs`'s `binary` reads `expr(lhs)` then `expr(rhs)` then
//! `arithmetic`, which emits the inner node's `rt_arith` *before* the outer's right operand is
//! touched -- the port's order, not the reference's. So the reordering happens in `optimize`,
//! between the tree above and the tree the emitter is handed, which is the coupling `tests/emit.rs`
//! records.
//!
//! Settling it means emitting without optimising and comparing there. It is not cosmetic: an
//! unbox can raise, so the order decides which diagnostic a body with two bad operands gives.
//!
//! **The corpus here is hand-written and small, and that is deliberate.** The reference optimises
//! before it lowers, so `1 + 2` reaches its emitter as `3` while this port's emitter sees the
//! addition; a shipped corpus would report that difference on every foldable constant and the
//! difference would be `opt.rs`'s rather than the emitter's. `tests/emit.rs` records the coupling.
//! Widening this corpus is what porting `fold_literals` would buy.

use ply_parser_spike_harness::{byte_literal, reference_emit_dump};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("the harness sits at <root>/spikes/ply-parser/harness")
        .to_path_buf()
}

fn spike_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the harness sits inside the spike")
        .to_path_buf()
}

/// The shipping binary, release first: `examples/desk.ply` is 160 kilobytes and the debug
/// interpreter is several times slower on it.
fn ply_binary() -> PathBuf {
    if let Ok(explicit) = std::env::var("PLY_BIN") {
        let path = PathBuf::from(explicit);
        assert!(
            path.exists(),
            "PLY_BIN names {}, which does not exist",
            path.display()
        );
        return path;
    }
    let root = repo_root();
    for profile in ["release", "debug"] {
        let candidate = root.join("target").join(profile).join("ply");
        if candidate.exists() {
            return candidate;
        }
    }
    panic!(
        "no `ply` binary at {}/target/{{release,debug}}/ply — run \
         `cargo build -p ply-cli --bin ply --release` first, or set PLY_BIN",
        root.display()
    );
}

/// The six modules the parser is, copied into a scratch project.
fn source_dir() -> PathBuf {
    match std::env::var("PLY_PARSER_SRC") {
        Ok(d) => PathBuf::from(d),
        Err(_) => spike_dir(),
    }
}

const MODULES: [&str; 9] = [
    "lexer.ply",
    "spine.ply",
    "types.ply",
    "patterns.ply",
    "exprs.ply",
    "items.ply",
    "rewrite.ply",
    "code.ply",
    "emit.ply",
];

struct Project(PathBuf);

impl Project {
    fn new(label: &str) -> Project {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "ply-parser-spike-{}-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed),
            label.replace(['/', '.'], "_")
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("a temp directory");
        for m in MODULES {
            std::fs::copy(source_dir().join(m), dir.join(m))
                .unwrap_or_else(|e| panic!("copying {m} from {}: {e}", source_dir().display()));
        }
        Project(dir)
    }

    /// One `ply run` for many inputs.
    fn dumps(&self, inputs: &[Vec<u8>]) -> Vec<String> {
        let mut src = String::from(
            "// Generated by spikes/ply-parser/harness/tests/emit_diff.rs. Not checked in.\n\
             import emit (emit_dump)\n",
        );
        let mut parts: Vec<String> = Vec::new();
        for (i, bytes) in inputs.iter().enumerate() {
            src.push_str(&format!("fn s{i}() -> Bytes = {}\n", byte_literal(bytes)));
            parts.push(format!("bytes_of_string(emit_dump(s{i}()))"));
            parts.push("b\"~\"".to_string());
        }
        src.push_str(&format!(
            "fn main() -> String = string_of_bytes(bytes_concat_all([{}]))\n",
            parts.join(", ")
        ));
        std::fs::write(self.0.join("probe.ply"), src).expect("write the probe");
        // The cache keys on the project's modules, and `probe.ply` changes every call, so this is
        // belt and braces — but a stale hit here would be a green comparison against a dump of some
        // other input, which is the one failure this harness must not have.
        let _ = std::fs::remove_dir_all(self.0.join(".ply-cache"));

        let out = Command::new(ply_binary())
            .arg("run")
            .args(backend_args())
            .arg(&self.0)
            .arg("--json")
            .output()
            .expect("run ply");
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        assert!(
            out.status.success(),
            "`ply run {}` failed ({}):\n{stdout}\n{stderr}",
            self.0.display(),
            out.status
        );
        let joined = extract_value(&stdout, &self.0);
        let mut parts: Vec<String> = joined.split('~').map(str::to_string).collect();
        let last = parts.pop().expect("split yields at least one part");
        assert!(
            last.is_empty() && parts.len() == inputs.len(),
            "the probe answered {} dumps for {} inputs",
            parts.len(),
            inputs.len()
        );
        parts
    }
}

impl Drop for Project {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// The `value` field of `ply run --json`, unwrapped.
fn extract_value(stdout: &str, dir: &Path) -> String {
    let needle = "\n  \"value\": \"";
    let occurrences = stdout.matches(needle).count();
    assert_eq!(
        occurrences,
        1,
        "`ply run {}` printed {occurrences} top-level `value` fields:\n{stdout}",
        dir.display()
    );
    let after = &stdout[stdout.find(needle).expect("checked above") + needle.len()..];
    let quote = "\\\"";
    assert!(
        after.starts_with(quote),
        "`ply run {}` answered with something that is not a rendered `String`:\n{stdout}",
        dir.display()
    );
    let rest = &after[quote.len()..];
    let end = rest
        .find(quote)
        .unwrap_or_else(|| panic!("the rendered `String` is never closed in:\n{stdout}"));
    let body = &rest[..end];
    // Emitted C has newlines in it, which `--json` escapes. The other differentials refuse an
    // escape because their dumps are printable ASCII by construction; this one decodes, and a
    // decoder written by hand rather than by `replace` because the escaping is layered and a
    // single pass leaves a stray backslash that reads as a difference in the C.
    // Twice, because the escaping is layered: `ply run --json` escapes the newline and the shell
    // capture escapes the escape, so one pass leaves the `n` behind and it reads as a difference
    // in the C rather than in the transport.
    let once = unescape(body);
    unescape(&once)
}

fn unescape(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    let mut it = body.chars().peekable();
    while let Some(c) = it.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match it.peek() {
            Some('n') => {
                it.next();
                out.push('\n');
            }
            Some('\\') => {
                it.next();
                out.push('\\');
            }
            _ => out.push(c),
        }
    }
    out
}

/// The bodies an emitter produced, by the name each is for.
fn by_name(dump: &str) -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    for record in dump.split(";f:").skip(1) {
        let Some((name, body)) = record.split_once(';') else {
            continue;
        };
        out.insert(name.to_string(), body.trim_end_matches(';').to_string());
    }
    out
}

/// Every body the port emitted is the body the reference emits.
fn compare(label: &str, inputs: &[(String, Vec<u8>)]) -> (usize, usize) {
    let project = Project::new(label);
    let texts: Vec<Vec<u8>> = inputs.iter().map(|(_, t)| t.clone()).collect();
    let got = project.dumps(&texts);
    let mut failures: Vec<String> = Vec::new();
    let (mut reached, mut available) = (0usize, 0usize);
    for ((name, text), actual) in inputs.iter().zip(&got) {
        let source = String::from_utf8_lossy(text).to_string();
        let expected = by_name(&reference_emit_dump(&[("m".to_string(), source)]));
        let mine = by_name(actual);
        available += expected.len();
        reached += mine.len();
        for (fname, body) in &mine {
            match expected.get(fname) {
                None => failures.push(format!(
                    "{label}: `{fname}` in {name} was emitted by the port and not by the reference"
                )),
                Some(want) if want != body => failures.push(format!(
                    "{label}: the two emitters disagree on `{fname}` in {name}:\n--- reference\n{want}\n--- port\n{body}"
                )),
                Some(_) => {}
            }
        }
    }
    println!("  {label}: {reached} of {available} body/bodies emitted, all agreeing");
    assert!(
        failures.is_empty(),
        "{} disagreement(s)\n\n{}",
        failures.len(),
        failures.join("\n")
    );
    (reached, available)
}

/// Every body the port emits is the body the reference emits, and it emits some.
#[test]
fn the_emitter_agrees_with_ply_codegen_wherever_the_port_reaches() {
    // Integer arithmetic over parameters: what the port covers, written out rather than mined, so
    // that widening the port means widening this list and nothing else.
    let programs: &[&str] = &[
        "fn g(a: Int, b: Int) -> Int = a * b\n",
        "fn h(a: Int, b: Int) -> Int = a + b\n",
        "fn k(a: Int, b: Int) -> Int = a - b\n",
        "fn d(a: Int, b: Int) -> Int = a / b\n",
        "fn r(a: Int, b: Int) -> Int = a % b\n",
        "fn lt(a: Int, b: Int) -> Bool = a < b\n",
        "fn le(a: Int, b: Int) -> Bool = a <= b\n",
        "fn gt(a: Int, b: Int) -> Bool = a > b\n",
        "fn ge(a: Int, b: Int) -> Bool = a >= b\n",
        "fn eq(a: Int, b: Int) -> Bool = a == b\n",
        "fn ne(a: Int, b: Int) -> Bool = a != b\n",
    ];
    let inputs: Vec<(String, Vec<u8>)> = programs
        .iter()
        .enumerate()
        .map(|(i, p)| (format!("program {i}"), p.as_bytes().to_vec()))
        .collect();
    let (reached, available) = compare("arithmetic", &inputs);
    // A port that emitted nothing would agree with the reference on every body it produced.
    assert_eq!(
        reached, available,
        "the port emitted {reached} of the {available} bodies the reference did"
    );
    assert!(reached >= 11, "only {reached} bodies were emitted");
}

/// `--backend` for every `ply` this differential runs.
fn backend_args() -> Vec<String> {
    match std::env::var("PLY_BACKEND").as_deref() {
        Ok("none") => Vec::new(),
        Ok(other) => vec!["--backend".to_string(), other.to_string()],
        Err(_) => vec!["--backend".to_string(), "cranelift".to_string()],
    }
}
