//! The fourth comparison: `infer.ply`'s check of a whole program — every definition's scheme,
//! footprint and constraints, every test's and law's footprint, every effect and constructor, or
//! the diagnostics — against `ply_core::check_program`'s, over the standard library, the standard
//! library with each example that uses no `derive`, and the programs the resolve comparison reads.

use ply_parser_spike_harness::{byte_literal, programs, records, reference_check_dump};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("the harness sits at <root>/spikes/ply-parser/harness")
        .to_path_buf()
}

fn spike_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the harness sits inside the spike")
        .to_path_buf()
}

fn ply_binary() -> PathBuf {
    if let Ok(explicit) = std::env::var("PLY_BIN") {
        return PathBuf::from(explicit);
    }
    let root = repo_root();
    for profile in ["release", "debug"] {
        let candidate = root.join("target").join(profile).join("ply");
        if candidate.exists() {
            return candidate;
        }
    }
    panic!("no `ply` binary; build one or set PLY_BIN");
}

fn source_dir() -> PathBuf {
    match std::env::var("PLY_PARSER_SRC") {
        Ok(d) => PathBuf::from(d),
        Err(_) => spike_dir(),
    }
}

const MODULES: [&str; 10] = [
    "lexer.ply",
    "spine.ply",
    "types.ply",
    "patterns.ply",
    "exprs.ply",
    "items.ply",
    "rewrite.ply",
    "resolve.ply",
    "tycore.ply",
    "infer.ply",
];

struct Project(PathBuf);

impl Project {
    fn new() -> Project {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "ply-infer-spike-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("a temp directory");
        for m in MODULES {
            std::fs::copy(source_dir().join(m), dir.join(m))
                .unwrap_or_else(|e| panic!("copying {m}: {e}"));
        }
        Project(dir)
    }

    /// One `ply run` for many programs, each a list of `(name, source)` modules.
    fn dumps(&self, inputs: &[Vec<(String, String)>]) -> Vec<String> {
        let mut src = String::from(
            "// Generated by spikes/ply-parser/harness/tests/infer.rs. Not checked in.\n\
             import infer (check_dump)\n",
        );
        let mut parts: Vec<String> = Vec::new();
        for (i, modules) in inputs.iter().enumerate() {
            let mut entries: Vec<String> = Vec::new();
            for (j, (name, text)) in modules.iter().enumerate() {
                src.push_str(&format!(
                    "fn n{i}_{j}() -> Bytes = {}\nfn s{i}_{j}() -> Bytes = {}\n",
                    byte_literal(name.as_bytes()),
                    byte_literal(text.as_bytes())
                ));
                entries.push(format!("{{ name: n{i}_{j}(), src: s{i}_{j}() }}"));
            }
            src.push_str(&format!(
                "fn p{i}() -> String = check_dump([{}])\n",
                entries.join(", ")
            ));
            parts.push(format!("bytes_of_string(p{i}())"));
            parts.push("b\"~\"".to_string());
        }
        src.push_str(&format!(
            "fn main() -> String = string_of_bytes(bytes_concat_all([{}]))\n",
            parts.join(", ")
        ));
        std::fs::write(self.0.join("probe.ply"), src).expect("write the probe");
        let _ = std::fs::remove_dir_all(self.0.join(".ply-cache"));
        let out = Command::new(ply_binary())
            .args(["run", "--json"])
            .arg(&self.0)
            .output()
            .expect("run ply");
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        assert!(
            out.status.success(),
            "`ply run {}` failed ({}):\n{stdout}\n{stderr}",
            self.0.display(),
            out.status
        );
        let joined = extract_value(&stdout);
        let mut parts: Vec<String> = joined.split('~').map(str::to_string).collect();
        let last = parts.pop().expect("split yields at least one part");
        assert!(
            last.is_empty() && parts.len() == inputs.len(),
            "the probe answered {} dumps for {} programs",
            parts.len(),
            inputs.len()
        );
        parts
    }
}

impl Drop for Project {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn extract_value(stdout: &str) -> String {
    let needle = "\n  \"value\": \"";
    let at = stdout
        .find(needle)
        .unwrap_or_else(|| panic!("no `value` field in:\n{stdout}"));
    let after = &stdout[at + needle.len()..];
    let quote = "\\\"";
    assert!(
        after.starts_with(quote),
        "not a rendered `String`:\n{stdout}"
    );
    let rest = &after[quote.len()..];
    let end = rest.find(quote).expect("the rendered `String` is closed");
    // The rendered string is JSON-escaped twice over: a backslash in a test label arrives as
    // `\\\\`, a quote as `\\\"`.
    rest[..end]
        .replace("\\\\\\\\", "\u{0}")
        .replace("\\\\\\\"", "\"")
        .replace('\u{0}', "\\")
}

fn first_difference(reference: &str, actual: &str) -> Option<String> {
    let want = records(reference);
    let got = records(actual);
    for i in 0..want.len().max(got.len()) {
        let a = want.get(i).copied();
        let b = got.get(i).copied();
        if a != b {
            let from = i.saturating_sub(6);
            let mut report = format!(
                "record {i} of {} differs\n  rust: {a:?}\n  ply : {b:?}\n  context (rust):\n",
                want.len()
            );
            for (j, r) in want.iter().enumerate().skip(from).take(14) {
                report.push_str(&format!("    {j:>7} {r}\n"));
            }
            report.push_str("  context (ply):\n");
            for (j, r) in got.iter().enumerate().skip(from).take(14) {
                report.push_str(&format!("    {j:>7} {r}\n"));
            }
            return Some(report);
        }
    }
    None
}

fn std_modules() -> Vec<(String, String)> {
    let dir = repo_root().join("crates/ply-std/ply");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("the standard library directory")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "ply"))
        .collect();
    files.sort();
    files
        .into_iter()
        .map(|p| {
            let stem = p.file_stem().unwrap().to_string_lossy().to_string();
            (
                format!("std.{stem}"),
                std::fs::read_to_string(&p).expect("UTF-8"),
            )
        })
        .collect()
}

fn examples() -> Vec<(String, String)> {
    let dir = repo_root().join("examples");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("the examples directory")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "ply"))
        .collect();
    files.sort();
    files
        .into_iter()
        .map(|p| {
            let stem = p.file_stem().unwrap().to_string_lossy().to_string();
            (stem, std::fs::read_to_string(&p).expect("UTF-8"))
        })
        .collect()
}

/// Runs `inputs` through both sides and reports every disagreement.
fn compare(label: &str, inputs: &[(String, Vec<(String, String)>)]) {
    let project = Project::new();
    let programs: Vec<Vec<(String, String)>> = inputs.iter().map(|(_, p)| p.clone()).collect();
    let got = project.dumps(&programs);
    let mut failures: Vec<String> = Vec::new();
    let mut records_total = 0usize;
    for ((name, program), actual) in inputs.iter().zip(&got) {
        let reference = reference_check_dump(program);
        records_total += records(&reference).len();
        if let Some(report) = first_difference(&reference, actual) {
            failures.push(format!(
                "{label}: the two resolvers disagree on {name}:\n{report}"
            ));
        }
    }
    println!(
        "  {label}: {} program(s), {records_total} records agree",
        inputs.len() - failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} of {} programs disagree\n\n{}",
        failures.len(),
        inputs.len(),
        failures.join("\n")
    );
}

#[test]
fn the_ply_checker_agrees_with_ply_core_on_the_standard_library() {
    compare(
        "std",
        &[("the standard library".to_string(), std_modules())],
    );
}

#[test]
fn the_ply_checker_agrees_with_ply_core_on_every_underived_example_with_the_standard_library() {
    let std = std_modules();
    let inputs: Vec<(String, Vec<(String, String)>)> = examples()
        .into_iter()
        // `ply_derive::expand_program` runs before the checker and the port has no deriver yet, so
        // an example with a `derive` is checked by neither side as the driver would check it.
        .filter(|(_, text)| !text.lines().any(|l| l.starts_with("derive ")))
        .map(|(name, text)| {
            let mut program = std.clone();
            program.push((name.clone(), text));
            (format!("std + examples/{name}.ply"), program)
        })
        .collect();
    compare("examples", &inputs);
}

#[test]
fn the_ply_checker_agrees_with_ply_core_on_the_resolvers_reference_programs() {
    let text = std::fs::read_to_string(spike_dir().join("fixtures/reference-programs.corpus"))
        .expect("the mined programs; run mine-programs.py");
    let inputs: Vec<(String, Vec<(String, String)>)> = programs(&text)
        .into_iter()
        .enumerate()
        .map(|(i, p)| (format!("reference-programs.corpus#{i}"), p))
        .collect();
    assert!(!inputs.is_empty(), "the mined bundle holds no program");
    compare("reference programs", &inputs);
}

#[test]
fn the_ply_checker_agrees_with_ply_core_on_the_resolvers_hand_written_programs() {
    let text = std::fs::read_to_string(spike_dir().join("fixtures/resolve-programs.corpus"))
        .expect("the hand-written programs");
    let inputs: Vec<(String, Vec<(String, String)>)> = programs(&text)
        .into_iter()
        .enumerate()
        .map(|(i, p)| (format!("resolve-programs.corpus#{i}"), p))
        .collect();
    assert!(
        !inputs.is_empty(),
        "the hand-written bundle holds no program"
    );
    compare("hand-written programs", &inputs);
}

/// The reference checker's own test inputs, each as a one-module program named `m`, the way
/// `crates/ply-core/src/tests.rs` checks them. Most are error paths, and the stage this port is
/// at does not raise every one the reference raises — so this reports the residue rather than
/// requiring agreement, and pins its size so it can only shrink.
#[test]
fn the_ply_checker_agrees_with_ply_core_on_the_references_own_inputs_up_to_the_pinned_residue() {
    let text = std::fs::read_to_string(spike_dir().join("fixtures/reference-checks.corpus"))
        .expect("the mined checker inputs; run mine-checks.py");
    let inputs: Vec<(String, Vec<(String, String)>)> = ply_parser_spike_harness::bundle(&text)
        .into_iter()
        .enumerate()
        .map(|(i, f)| {
            (
                format!("reference-checks.corpus#{i}"),
                vec![("m".to_string(), f)],
            )
        })
        .collect();
    assert!(!inputs.is_empty());
    let project = Project::new();
    let programs: Vec<Vec<(String, String)>> = inputs.iter().map(|(_, p)| p.clone()).collect();
    let got = project.dumps(&programs);
    let mut disagree: Vec<String> = Vec::new();
    for ((name, program), actual) in inputs.iter().zip(&got) {
        let reference = reference_check_dump(program);
        if first_difference(&reference, actual).is_some() {
            let code = reference
                .split(';')
                .find(|r| r.starts_with('!'))
                .map(|r| {
                    r.split(':')
                        .next()
                        .unwrap_or(r)
                        .trim_start_matches('!')
                        .to_string()
                })
                .unwrap_or_else(|| "ok".to_string());
            disagree.push(format!("{name} ({code})"));
        }
    }
    println!(
        "  reference checks: {} of {} inputs agree; the residue: {:?}",
        inputs.len() - disagree.len(),
        inputs.len(),
        disagree
    );
    assert!(
        disagree.len() <= RESIDUE,
        "the residue grew to {} past the pinned {RESIDUE}: {disagree:?}",
        disagree.len()
    );
}

/// The inputs above the port does not yet agree on, pinned so that a port of one more pass
/// lowers it and a regression raises it.
const RESIDUE: usize = 13;
