//! The seventh comparison: `code.ply`'s lowering against `ply_eval::code::lower_fn`.
//!
//! The first differential for a stage *after* the front end, and the one that makes converting the
//! C emitter to Ply a thing that can be done incrementally at all: the emitter reads the lowered
//! form, so a port of it has to produce that form, and this is what says whether it has.
//!
//! **It compares only what `code.ply` claims to lower.** `lower` answers `None` for a node kind
//! the port has not reached, `lower_module` leaves that function out of its dump, and this test
//! compares the functions that *are* there against the oracle's records for the same names. A port
//! that lowered nothing would pass every comparison and fail `the_port_reaches_a_growing_share`,
//! which is the assertion that keeps this honest as the port grows.

use ply_parser_spike_harness::{byte_literal, reference_lower_dump};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("the harness sits at <root>/spikes/ply-parser/harness")
        .to_path_buf()
}

fn spike_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the harness sits inside the spike")
        .to_path_buf()
}

/// The shipping binary, release first: `examples/desk.ply` is 160 kilobytes and the debug
/// interpreter is several times slower on it.
fn ply_binary() -> PathBuf {
    if let Ok(explicit) = std::env::var("PLY_BIN") {
        let path = PathBuf::from(explicit);
        assert!(
            path.exists(),
            "PLY_BIN names {}, which does not exist",
            path.display()
        );
        return path;
    }
    let root = repo_root();
    for profile in ["release", "debug"] {
        let candidate = root.join("target").join(profile).join("ply");
        if candidate.exists() {
            return candidate;
        }
    }
    panic!(
        "no `ply` binary at {}/target/{{release,debug}}/ply — run \
         `cargo build -p ply-cli --bin ply --release` first, or set PLY_BIN",
        root.display()
    );
}

/// The six modules the parser is, copied into a scratch project.
fn source_dir() -> PathBuf {
    match std::env::var("PLY_PARSER_SRC") {
        Ok(d) => PathBuf::from(d),
        Err(_) => spike_dir(),
    }
}

const MODULES: [&str; 8] = [
    "lexer.ply",
    "spine.ply",
    "types.ply",
    "patterns.ply",
    "exprs.ply",
    "items.ply",
    "rewrite.ply",
    "code.ply",
];

struct Project(PathBuf);

impl Project {
    fn new(label: &str) -> Project {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "ply-parser-spike-{}-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed),
            label.replace(['/', '.'], "_")
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("a temp directory");
        for m in MODULES {
            std::fs::copy(source_dir().join(m), dir.join(m))
                .unwrap_or_else(|e| panic!("copying {m} from {}: {e}", source_dir().display()));
        }
        Project(dir)
    }

    /// One `ply run` for many inputs.
    fn dumps(&self, inputs: &[Vec<u8>]) -> Vec<String> {
        let mut src = String::from(
            "// Generated by spikes/ply-parser/harness/tests/lower_diff.rs. Not checked in.\n\
             import code (lower_dump)\n",
        );
        let mut parts: Vec<String> = Vec::new();
        for (i, bytes) in inputs.iter().enumerate() {
            src.push_str(&format!("fn s{i}() -> Bytes = {}\n", byte_literal(bytes)));
            parts.push(format!("bytes_of_string(lower_dump(s{i}()))"));
            parts.push("b\"~\"".to_string());
        }
        src.push_str(&format!(
            "fn main() -> String = string_of_bytes(bytes_concat_all([{}]))\n",
            parts.join(", ")
        ));
        std::fs::write(self.0.join("probe.ply"), src).expect("write the probe");
        // The cache keys on the project's modules, and `probe.ply` changes every call, so this is
        // belt and braces — but a stale hit here would be a green comparison against a dump of some
        // other input, which is the one failure this harness must not have.
        let _ = std::fs::remove_dir_all(self.0.join(".ply-cache"));

        let out = Command::new(ply_binary())
            .arg("run")
            .args(backend_args())
            .arg(&self.0)
            .arg("--json")
            .output()
            .expect("run ply");
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        assert!(
            out.status.success(),
            "`ply run {}` failed ({}):\n{stdout}\n{stderr}",
            self.0.display(),
            out.status
        );
        let joined = extract_value(&stdout, &self.0);
        let mut parts: Vec<String> = joined.split('~').map(str::to_string).collect();
        let last = parts.pop().expect("split yields at least one part");
        assert!(
            last.is_empty() && parts.len() == inputs.len(),
            "the probe answered {} dumps for {} inputs",
            parts.len(),
            inputs.len()
        );
        parts
    }
}

impl Drop for Project {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// The `value` field of `ply run --json`, unwrapped.
fn extract_value(stdout: &str, dir: &Path) -> String {
    let needle = "\n  \"value\": \"";
    let occurrences = stdout.matches(needle).count();
    assert_eq!(
        occurrences,
        1,
        "`ply run {}` printed {occurrences} top-level `value` fields:\n{stdout}",
        dir.display()
    );
    let after = &stdout[stdout.find(needle).expect("checked above") + needle.len()..];
    let quote = "\\\"";
    assert!(
        after.starts_with(quote),
        "`ply run {}` answered with something that is not a rendered `String`:\n{stdout}",
        dir.display()
    );
    let rest = &after[quote.len()..];
    let end = rest
        .find(quote)
        .unwrap_or_else(|| panic!("the rendered `String` is never closed in:\n{stdout}"));
    let body = &rest[..end];
    assert!(
        !body.contains('\\') && !body.contains('"'),
        "the Ply dump holds a character `ply run --json` escapes, so it is not the \
         printable-ASCII form the comparison assumes:\n{body}"
    );
    body.to_string()
}

/// The first record the two dumps disagree on, with context, or `None`.
fn ply_files(dir: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "ply"))
        .collect();
    out.sort();
    out
}

/// The records `code.ply` produced, by the function name each is for.
///
/// The port leaves out what it cannot lower, so a comparison keyed on position would compare a
/// record against the wrong function the moment one was skipped. Keyed on the name, a skipped
/// function is simply absent and the ones present are compared against their own reference.
fn by_name(dump: &str) -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    for record in dump.split(";f:").skip(1) {
        let Some((head, body)) = record.split_once(';') else {
            continue;
        };
        let name = head.split(':').next().unwrap_or_default().to_string();
        out.insert(name, body.trim_end_matches(';').to_string());
    }
    out
}

/// What the port covers, over one corpus: every function it lowered agrees with the oracle, and
/// the share it reached is reported so that a port going backwards is visible.
fn compare(label: &str, inputs: &[(String, Vec<u8>)]) -> (usize, usize) {
    let project = Project::new(label);
    let texts: Vec<Vec<u8>> = inputs.iter().map(|(_, t)| t.clone()).collect();
    let got = project.dumps(&texts);
    let mut failures: Vec<String> = Vec::new();
    let (mut reached, mut available) = (0usize, 0usize);
    for ((name, text), actual) in inputs.iter().zip(&got) {
        let source = String::from_utf8_lossy(text).to_string();
        let reference = reference_lower_dump(&[("m".to_string(), source)]);
        let expected = by_name(&reference);
        let mine = by_name(actual);
        available += expected.len();
        reached += mine.len();
        for (fname, body) in &mine {
            // A record update is not covered. `rewrite.ply` expands `{..b, f: e}` into a record
            // that names every field; `ply-syntax` keeps it as a node with `copies` and `sets`,
            // which `code.rs` lowers to `RecordUpdate`. So the two are lowering different trees
            // here, and comparing them would report a difference that is neither one's fault.
            // Excluded by what the *oracle* holds, so a port that started emitting updates would
            // still be compared.
            if expected
                .get(fname)
                .is_some_and(|want| want.contains("upd("))
            {
                continue;
            }
            match expected.get(fname) {
                None => failures.push(format!(
                    "{label}: `{fname}` in {name} was lowered by the port and not by the oracle"
                )),
                Some(want) if want != body => failures.push(format!(
                    "{label}: the two lowerings disagree on `{fname}` in {name}:\n  oracle {want}\n  port   {body}"
                )),
                Some(_) => {}
            }
        }
    }
    println!(
        "  {label}: {} input(s), {reached} of {available} function(s) lowered, all agreeing",
        inputs.len()
    );
    assert!(
        failures.is_empty(),
        "{} disagreement(s)\n\n{}",
        failures.len(),
        failures.join("\n")
    );
    (reached, available)
}

fn files_in(dir: &Path) -> Vec<(String, Vec<u8>)> {
    ply_files(dir)
        .into_iter()
        .map(|p| {
            (
                p.display().to_string(),
                std::fs::read(&p).expect("readable"),
            )
        })
        .collect()
}

/// The port lowers what it says it lowers, and agrees wherever it does.
#[test]
fn the_lowering_agrees_with_ply_eval_wherever_the_port_reaches() {
    let mut reached = 0usize;
    let mut available = 0usize;
    for (label, dir) in [
        ("stdlib", repo_root().join("crates/ply-std/ply")),
        ("examples", repo_root().join("examples")),
        ("fixtures", spike_dir().join("fixtures")),
    ] {
        let (r, a) = compare(label, &files_in(&dir));
        reached += r;
        available += a;
    }
    // The assertion that keeps the one above honest: a port that lowered nothing would agree with
    // the oracle on every function it produced, because it would produce none. This is the share,
    // and it is written down so that raising it is a visible change and lowering it is a failure.
    println!("  the port reaches {reached} of {available} function bodies");
    assert!(
        reached >= 1060,
        "the port lowered {reached} of {available} bodies, and it reached 1060 when this was \
         written -- raise this number when the port grows, and never lower it"
    );
}

/// `--backend` for every `ply` this differential runs: `cranelift` unless `PLY_BACKEND` names
/// another, and nothing at all for `none`.
fn backend_args() -> Vec<String> {
    match std::env::var("PLY_BACKEND").as_deref() {
        Ok("none") => Vec::new(),
        Ok(other) => vec!["--backend".to_string(), other.to_string()],
        Err(_) => vec!["--backend".to_string(), "cranelift".to_string()],
    }
}
