//! The third comparison: `rewrite.ply` — the effect-set, record-update and try-operator rewrites
//! `Parser::run` applies after the grammar — against `ply_syntax::parse_recovering`, tree and
//! diagnostics, over every input the parser differential reads.

use ply_parser_spike_harness::{bundle, byte_literal, records, reference_dump_expanded};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("the harness sits at <root>/spikes/ply-parser/harness")
        .to_path_buf()
}

fn spike_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the harness sits inside the spike")
        .to_path_buf()
}

/// The shipping binary, release first: `examples/desk.ply` is 160 kilobytes and the debug
/// interpreter is several times slower on it.
fn ply_binary() -> PathBuf {
    if let Ok(explicit) = std::env::var("PLY_BIN") {
        let path = PathBuf::from(explicit);
        assert!(
            path.exists(),
            "PLY_BIN names {}, which does not exist",
            path.display()
        );
        return path;
    }
    let root = repo_root();
    for profile in ["release", "debug"] {
        let candidate = root.join("target").join(profile).join("ply");
        if candidate.exists() {
            return candidate;
        }
    }
    panic!(
        "no `ply` binary at {}/target/{{release,debug}}/ply — run \
         `cargo build -p ply-cli --bin ply --release` first, or set PLY_BIN",
        root.display()
    );
}

/// The six modules the parser is, copied into a scratch project.
fn source_dir() -> PathBuf {
    match std::env::var("PLY_PARSER_SRC") {
        Ok(d) => PathBuf::from(d),
        Err(_) => spike_dir(),
    }
}

const MODULES: [&str; 7] = [
    "lexer.ply",
    "spine.ply",
    "types.ply",
    "patterns.ply",
    "exprs.ply",
    "items.ply",
    "rewrite.ply",
];

struct Project(PathBuf);

impl Project {
    fn new(label: &str) -> Project {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "ply-parser-spike-{}-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed),
            label.replace(['/', '.'], "_")
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("a temp directory");
        for m in MODULES {
            std::fs::copy(source_dir().join(m), dir.join(m))
                .unwrap_or_else(|e| panic!("copying {m} from {}: {e}", source_dir().display()));
        }
        Project(dir)
    }

    /// One `ply run` for many inputs.
    fn dumps(&self, inputs: &[Vec<u8>]) -> Vec<String> {
        let mut src = String::from(
            "// Generated by spikes/ply-parser/harness/tests/agreement.rs. Not checked in.\n\
             import rewrite (dump_expanded)\n",
        );
        let mut parts: Vec<String> = Vec::new();
        for (i, bytes) in inputs.iter().enumerate() {
            src.push_str(&format!("fn s{i}() -> Bytes = {}\n", byte_literal(bytes)));
            parts.push(format!("bytes_of_string(dump_expanded(s{i}()))"));
            parts.push("b\"~\"".to_string());
        }
        src.push_str(&format!(
            "fn main() -> String = string_of_bytes(bytes_concat_all([{}]))\n",
            parts.join(", ")
        ));
        std::fs::write(self.0.join("probe.ply"), src).expect("write the probe");
        // The cache keys on the project's modules, and `probe.ply` changes every call, so this is
        // belt and braces — but a stale hit here would be a green comparison against a dump of some
        // other input, which is the one failure this harness must not have.
        let _ = std::fs::remove_dir_all(self.0.join(".ply-cache"));

        let out = Command::new(ply_binary())
            .arg("run")
            .arg(&self.0)
            .arg("--json")
            .output()
            .expect("run ply");
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        assert!(
            out.status.success(),
            "`ply run {}` failed ({}):\n{stdout}\n{stderr}",
            self.0.display(),
            out.status
        );
        let joined = extract_value(&stdout, &self.0);
        let mut parts: Vec<String> = joined.split('~').map(str::to_string).collect();
        let last = parts.pop().expect("split yields at least one part");
        assert!(
            last.is_empty() && parts.len() == inputs.len(),
            "the probe answered {} dumps for {} inputs",
            parts.len(),
            inputs.len()
        );
        parts
    }
}

impl Drop for Project {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// The `value` field of `ply run --json`, unwrapped.
fn extract_value(stdout: &str, dir: &Path) -> String {
    let needle = "\n  \"value\": \"";
    let occurrences = stdout.matches(needle).count();
    assert_eq!(
        occurrences,
        1,
        "`ply run {}` printed {occurrences} top-level `value` fields:\n{stdout}",
        dir.display()
    );
    let after = &stdout[stdout.find(needle).expect("checked above") + needle.len()..];
    let quote = "\\\"";
    assert!(
        after.starts_with(quote),
        "`ply run {}` answered with something that is not a rendered `String`:\n{stdout}",
        dir.display()
    );
    let rest = &after[quote.len()..];
    let end = rest
        .find(quote)
        .unwrap_or_else(|| panic!("the rendered `String` is never closed in:\n{stdout}"));
    let body = &rest[..end];
    assert!(
        !body.contains('\\') && !body.contains('"'),
        "the Ply dump holds a character `ply run --json` escapes, so it is not the \
         printable-ASCII form the comparison assumes:\n{body}"
    );
    body.to_string()
}

/// The first record the two dumps disagree on, with context, or `None`.
fn first_difference(reference: &str, actual: &str) -> Option<String> {
    let want = records(reference);
    let got = records(actual);
    for i in 0..want.len().max(got.len()) {
        let a = want.get(i).copied();
        let b = got.get(i).copied();
        if a != b {
            let from = i.saturating_sub(6);
            let mut report = format!("record {i} of {} differs\n", want.len());
            report.push_str(&format!(
                "  rust: {a:?}\n  ply : {b:?}\n  context (rust):\n"
            ));
            for (j, r) in want.iter().enumerate().skip(from).take(14) {
                report.push_str(&format!("    {j:>7} {r}\n"));
            }
            report.push_str("  context (ply):\n");
            for (j, r) in got.iter().enumerate().skip(from).take(14) {
                report.push_str(&format!("    {j:>7} {r}\n"));
            }
            return Some(report);
        }
    }
    None
}

fn ply_files(dir: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "ply"))
        .collect();
    out.sort();
    out
}

fn compare(label: &str, inputs: &[(String, Vec<u8>)]) {
    let project = Project::new(label);
    let texts: Vec<Vec<u8>> = inputs.iter().map(|(_, t)| t.clone()).collect();
    let got = project.dumps(&texts);
    let mut failures: Vec<String> = Vec::new();
    let mut total = 0usize;
    for ((name, text), actual) in inputs.iter().zip(&got) {
        let reference = reference_dump_expanded(&String::from_utf8_lossy(text));
        total += records(&reference).len();
        if let Some(report) = first_difference(&reference, actual) {
            failures.push(format!(
                "{label}: the two rewrites disagree on {name}:\n{report}"
            ));
        }
    }
    println!(
        "  {label}: {} input(s), {total} records agree",
        inputs.len() - failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} of {} inputs disagree\n\n{}",
        failures.len(),
        inputs.len(),
        failures.join("\n")
    );
}

fn files_in(dir: &Path) -> Vec<(String, Vec<u8>)> {
    ply_files(dir)
        .into_iter()
        .map(|p| {
            (
                p.display().to_string(),
                std::fs::read(&p).expect("readable"),
            )
        })
        .collect()
}

#[test]
fn the_rewrites_agree_with_ply_syntax_on_every_example() {
    compare("examples", &files_in(&repo_root().join("examples")));
}

#[test]
fn the_rewrites_agree_with_ply_syntax_on_the_shipped_standard_library() {
    compare("stdlib", &files_in(&repo_root().join("crates/ply-std/ply")));
}

#[test]
fn the_rewrites_agree_with_ply_syntax_on_the_hand_written_fixtures() {
    compare("fixtures", &files_in(&spike_dir().join("fixtures")));
}

#[test]
fn the_rewrites_agree_with_ply_syntax_on_the_reference_own_test_inputs() {
    let text = std::fs::read_to_string(spike_dir().join("fixtures/reference-tests.corpus"))
        .expect("the mined corpus");
    let inputs: Vec<(String, Vec<u8>)> = bundle(&text)
        .into_iter()
        .enumerate()
        .map(|(i, f)| (format!("reference-tests.corpus#{i}"), f.into_bytes()))
        .collect();
    assert!(!inputs.is_empty());
    compare("reference inputs", &inputs);
}
