[package]
name = "ply-host"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ply-core = { workspace = true }
ply-eval = { workspace = true }
ply-span = { workspace = true }
ply-std = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }

[dev-dependencies]
ply-syntax = { workspace = true }
rcgen = { workspace = true }
tempfile = { workspace = true }
