//! Generates the launcher's tables of the `ply` program's sources from the packages themselves: the
//! CLI package and everything it depends on by path, every module named by its stem and every
//! package's manifest, keyed by the package's path relative to the repository. The keys are what
//! makes a stage built from these tables the same shape as the checkout, so a `Path(..)`
//! dependency resolves the same way in both. Both land in dep-info through the `include_str!`s the
//! generated table holds.
//!
//! The dependency walk reads the manifest's text for `Path("...")` and nothing else: a build script
//! needs the *files*, and the meaning of a manifest is the front end's (`crates/ply-compiler/ply/
//! pkg.ply`), which this deliberately does not duplicate.
//!
//! The runtime's stamp digests sources, not the binary, so both build profiles file the same.

#[path = "src/code.rs"]
mod code;

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

/// What runs a test or a law. `ply-host` is not: every handler it serves is nondeterministic, so
/// nothing a store keeps reached it, which `ply-host-tests` holds it to.
const RUNTIME: &[&str] = &["ply-eval", "ply-codegen", "ply-machine"];

fn main() {
    let repo = code::normalize(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../.."));
    let root = repo.join("crates/ply-cli/ply");
    let lock = std::fs::read_to_string(repo.join("Cargo.lock")).expect("Cargo.lock reads");
    println!(
        "cargo:rerun-if-changed={}",
        repo.join("Cargo.lock").display()
    );
    println!(
        "cargo:rustc-env=PLY_RUNTIME_SOURCES={}",
        digest(
            &repo,
            &crate_files(&repo, RUNTIME),
            &[code::lock_closure(&lock, RUNTIME).as_bytes()]
        )
    );
    let packages = closure(&root);

    // The root package's own modules, as every consumer that names one looks them up.
    let mut out = String::from(
        "/// The program `ply` runs, one module per file of `crates/ply-cli/ply`, each named by\n\
         /// its stem. Generated by `build.rs` from the package directory.\n\
         pub const PROGRAM_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (name, text) in modules(&root) {
        out.push_str(&format!("    ({name:?}, include_str!({text:?})),\n"));
    }
    out.push_str("];\n");

    out.push_str(
        "\n/// Every package this binary ships — the CLI and everything it depends on by path, the\n\
         /// root first — as `(package path relative to the repository, module, text)`.\n\
         pub const PROGRAM_PACKAGES: &[(&str, &str, &str)] = &[\n",
    );
    for (dir, key) in &packages {
        for (name, text) in modules(dir) {
            out.push_str(&format!(
                "    ({key:?}, {name:?}, include_str!({:?})),\n",
                text.display().to_string()
            ));
        }
    }
    out.push_str(
        "];\n\n/// Those packages' manifests, under the same keys and in the same order.\n\
         pub const PROGRAM_PACKAGE_MANIFESTS: &[(&str, &str)] = &[\n",
    );
    for (dir, key) in &packages {
        out.push_str(&format!(
            "    ({key:?}, include_str!({:?})),\n",
            manifest(dir).display().to_string()
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set for a build script");
    std::fs::write(Path::new(&out_dir).join("program_sources.rs"), out)
        .expect("the generated table is written");
}

/// The CLI package and, breadth-first, every package it depends on by path: `(directory, key)` with
/// the root first. A package reachable twice is laid out once.
fn closure(root: &Path) -> Vec<(PathBuf, String)> {
    let repo = code::normalize(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../.."));
    let mut seen: BTreeSet<PathBuf> = BTreeSet::new();
    let mut out: Vec<(PathBuf, String)> = Vec::new();
    let mut queue: Vec<PathBuf> = vec![code::normalize(root)];
    while let Some(dir) = queue.pop() {
        if !seen.insert(dir.clone()) {
            continue;
        }
        let file = manifest(&dir);
        assert!(
            file.is_file(),
            "a package this binary ships holds a ply.pkg at {}",
            file.display()
        );
        println!("cargo:rerun-if-changed={}", file.display());
        queue.extend(code::path_dependencies(&file));
        let key = dir
            .strip_prefix(&repo)
            .unwrap_or_else(|_| panic!("{} is inside the repository", dir.display()))
            .to_string_lossy()
            .into_owned();
        out.push((dir, key));
    }
    out
}

fn manifest(dir: &Path) -> PathBuf {
    dir.join("ply.pkg")
}

/// The `.ply` modules of one package, ascending by stem, as `(name, path)`.
fn modules(dir: &Path) -> Vec<(String, PathBuf)> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut out: Vec<(String, PathBuf)> = Vec::new();
    for entry in std::fs::read_dir(dir).unwrap_or_else(|e| {
        panic!("the package directory {} reads: {e}", dir.display());
    }) {
        let path = entry.expect("a directory entry").path();
        if path.extension().is_some_and(|x| x == "ply") {
            println!("cargo:rerun-if-changed={}", path.display());
            let name = path
                .file_stem()
                .expect("a .ply file has a stem")
                .to_string_lossy()
                .into_owned();
            out.push((name, path));
        }
    }
    out.sort();
    out
}

/// Every file under each crate's `src/`, and each crate's manifest.
fn crate_files(repo: &Path, crates: &[&str]) -> Vec<PathBuf> {
    let mut paths = Vec::new();
    for name in crates {
        let dir = repo.join("crates").join(name);
        println!("cargo:rerun-if-changed={}", dir.join("src").display());
        walk(&dir.join("src"), &mut paths);
        paths.push(dir.join("Cargo.toml"));
    }
    paths
}

/// The files keyed by their paths relative to the repository, then `extra`.
fn digest(repo: &Path, files: &[PathBuf], extra: &[&[u8]]) -> String {
    let mut paths = files.to_vec();
    paths.sort();
    paths.dedup();
    let mut h = blake3::Hasher::new();
    for path in &paths {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path
            .strip_prefix(repo)
            .expect("every file digested is in the repository")
            .to_string_lossy()
            .into_owned();
        let bytes = std::fs::read(path)
            .unwrap_or_else(|e| panic!("the source file {} reads: {e}", path.display()));
        h.update(&(name.len() as u64).to_le_bytes());
        h.update(name.as_bytes());
        h.update(&(bytes.len() as u64).to_le_bytes());
        h.update(&bytes);
    }
    for bytes in extra {
        h.update(&(bytes.len() as u64).to_le_bytes());
        h.update(bytes);
    }
    h.finalize().to_hex().to_string()
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("the source directory {} reads: {e}", dir.display()))
    {
        let path = entry.expect("a directory entry").path();
        if path.is_dir() {
            walk(&path, out);
        } else {
            out.push(path);
        }
    }
}
