//! Generates the launcher's tables of the `ply` program's sources from the packages themselves: the
//! CLI package and everything it depends on by path, every module named by its stem and every
//! package's manifest, keyed by the package's path relative to the repository. The keys are what
//! makes a stage built from these tables the same shape as the checkout, so a `Path(..)`
//! dependency resolves the same way in both. Both land in dep-info through the `include_str!`s the
//! generated table holds.
//!
//! The dependency walk reads the manifest's text for `Path("...")` and nothing else: a build script
//! needs the *files*, and the meaning of a manifest is the front end's (`crates/ply-compiler/ply/
//! pkg.ply`), which this deliberately does not duplicate.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn main() {
    let repo = normalize(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../.."));
    let root = repo.join("crates/ply-cli/ply");
    let packages = closure(&root);

    // The root package's own modules, as every consumer that names one looks them up.
    let mut out = String::from(
        "/// The program `ply` runs, one module per file of `crates/ply-cli/ply`, each named by\n\
         /// its stem. Generated by `build.rs` from the package directory.\n\
         pub const PROGRAM_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (name, text) in modules(&root) {
        out.push_str(&format!("    ({name:?}, include_str!({text:?})),\n"));
    }
    out.push_str(
        "];\n\n/// The CLI package's manifest.\n\
         pub const PROGRAM_MANIFEST: &str = include_str!(",
    );
    out.push_str(&format!("{:?});\n", manifest(&root).display().to_string()));

    out.push_str(
        "\n/// Every package this binary ships — the CLI and everything it depends on by path, the\n\
         /// root first — as `(package path relative to the repository, module, text)`.\n\
         pub const PROGRAM_PACKAGES: &[(&str, &str, &str)] = &[\n",
    );
    for (dir, key) in &packages {
        for (name, text) in modules(dir) {
            out.push_str(&format!(
                "    ({key:?}, {name:?}, include_str!({:?})),\n",
                text.display().to_string()
            ));
        }
    }
    out.push_str(
        "];\n\n/// Those packages' manifests, under the same keys and in the same order.\n\
         pub const PROGRAM_PACKAGE_MANIFESTS: &[(&str, &str)] = &[\n",
    );
    for (dir, key) in &packages {
        out.push_str(&format!(
            "    ({key:?}, include_str!({:?})),\n",
            manifest(dir).display().to_string()
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set for a build script");
    std::fs::write(Path::new(&out_dir).join("program_sources.rs"), out)
        .expect("the generated table is written");
}

/// The CLI package and, breadth-first, every package it depends on by path: `(directory, key)` with
/// the root first. A package reachable twice is laid out once.
fn closure(root: &Path) -> Vec<(PathBuf, String)> {
    let repo = normalize(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../.."));
    let mut seen: BTreeSet<PathBuf> = BTreeSet::new();
    let mut out: Vec<(PathBuf, String)> = Vec::new();
    let mut queue: Vec<PathBuf> = vec![normalize(root)];
    while let Some(dir) = queue.pop() {
        if !seen.insert(dir.clone()) {
            continue;
        }
        let file = manifest(&dir);
        assert!(
            file.is_file(),
            "a package this binary ships holds a ply.pkg at {}",
            file.display()
        );
        println!("cargo:rerun-if-changed={}", file.display());
        let text = std::fs::read_to_string(&file).expect("a manifest reads");
        for dep in path_dependencies(&text) {
            queue.push(normalize(&dir.join(dep)));
        }
        let key = dir
            .strip_prefix(&repo)
            .unwrap_or_else(|_| panic!("{} is inside the repository", dir.display()))
            .to_string_lossy()
            .into_owned();
        out.push((dir, key));
    }
    out
}

fn manifest(dir: &Path) -> PathBuf {
    dir.join("ply.pkg")
}

/// Every `Path("...")` a manifest names, as written: a build script needs the directories, not the
/// resolution.
fn path_dependencies(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(at) = rest.find("Path(\"") {
        rest = &rest[at + "Path(\"".len()..];
        match rest.find('"') {
            Some(end) => {
                out.push(rest[..end].to_string());
                rest = &rest[end + 1..];
            }
            None => break,
        }
    }
    out
}

/// The `.ply` modules of one package, ascending by stem, as `(name, path)`.
fn modules(dir: &Path) -> Vec<(String, PathBuf)> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut out: Vec<(String, PathBuf)> = Vec::new();
    for entry in std::fs::read_dir(dir).unwrap_or_else(|e| {
        panic!("the package directory {} reads: {e}", dir.display());
    }) {
        let path = entry.expect("a directory entry").path();
        if path.extension().is_some_and(|x| x == "ply") {
            println!("cargo:rerun-if-changed={}", path.display());
            let name = path
                .file_stem()
                .expect("a .ply file has a stem")
                .to_string_lossy()
                .into_owned();
            out.push((name, path));
        }
    }
    out.sort();
    out
}

/// Lexical, because a dependency is written as `../../x` and `Path::join` keeps the `..`s: the keys
/// have to line up with the repository's own paths.
fn normalize(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for part in path.components() {
        match part {
            std::path::Component::ParentDir => {
                out.pop();
            }
            std::path::Component::CurDir => {}
            other => out.push(other.as_os_str()),
        }
    }
    out
}
