[package]
name = "ply-hash"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ply-span = { workspace = true }
ply-syntax = { workspace = true }
ply-core = { workspace = true }
blake3 = { workspace = true }
serde = { workspace = true }
rustc-hash = { workspace = true }
indexmap = { workspace = true }
stacker = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
