[package]
name = "ply-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ply-span = { workspace = true }
ply-syntax = { workspace = true }
ply-core = { workspace = true }
ply-hash = { workspace = true }
ply-eval = { workspace = true }
ply-store = { workspace = true }
ply-test = { workspace = true }
indexmap = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
tempfile = { workspace = true }
