[package]
name = "ply-cli-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
ply-span = { workspace = true }
ply-ty = { workspace = true }
ply-eval = { workspace = true }
ply-store = { workspace = true }
ply-test = { workspace = true }
ply-prove = { workspace = true }
ply-host = { workspace = true }
ply-std = { workspace = true }
ply-cli = { workspace = true }
ply-codegen = { workspace = true }
assert_cmd = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
rcgen = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
