[package]
name = "ply-eval"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ply-span = { workspace = true }
ply-syntax = { workspace = true }
ply-core = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
